security:
    enable_authenticator_manager: true
     
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            custom_authenticator: App\Security\LoginformAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route
       
  
    

    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
          
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN } 
        - { path: ^/compte, roles: ROLE_USER }
        - { path: ^/checkout, roles: ROLE_USER }       

          

when@test:
   
